### PR TITLE
All functions must be defined before any are used.

### PR DESCRIPTION
**Pull request by TiberiumPY**
Fixed error

### CODE REVIEW

**Comment by daniktheboss** [comment]
Blame xtreamplayzcode... he "tested" the code

**Comment by daniktheboss** [comment]
Wait... and if u do makedirs () and then Def makedirs() you call the function and then define it

**Comment by TiberiumPY** [comment]
Well.. Yes
I tried the wizard, and it isn't worked

**Comment by TiberiumPY** [comment]
He threw an error, and I fixed it

**Comment by daniktheboss** [comment]
Ok I'll come back to the installer last part... working on logger right now :D

**Comment by XtremePlayzCODE** [comment]
lmao.exe

**Comment by TiberiumPY** [comment]
why do u don't merge it?

**Comment by XtremePlayzCODE** [comment]
why did you not merge it?**

**Comment by TiberiumPY** [comment]
I don't know English very well

**Comment by daniktheboss** [comment]
I will come back to installer later

**Comment by TiberiumPY** [comment]
omg

**Comment by TiberiumPY** [comment]
Why did you started work on f**king installer, if you even don't have any server implementation? This is silly...

**Comment by daniktheboss** [comment]
Because I am doing everything little by little... I can start where ever I want!

**Pull request closed without merging**
