### PR TITLE
Updated installer and configuration

### PR DESCRIPTION
**Pull request by XtremePlayzCODE**
Note: **NOT EVERYONE HAS LINUX. DO NOT USE LINUX DIRS! USE RELATIVE DIRS!**

### CODE REVIEW

**Comment by daniktheboss** [comment]
Have you tested this code?

**Comment by XtremePlayzCODE** [comment]
Yes

**Comment by XtremePlayzCODE** [comment]
Well apparently not...

**Comment by XtremePlayzCODE** [comment]
XD

**Pull request merged**
